//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2_2Task.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employeee
    {

        public int ID { get; set; }
        [Required]
        [StringLength(12, ErrorMessage = "The {0} must be between {2} - {1} characters long.", MinimumLength = 1)]
        public string First_Name { get; set; }
        [Required]
        [StringLength(12, ErrorMessage = "The {0} must be between {2} - {1} characters long.", MinimumLength = 1)]
        public string Last_Nama { get; set; }
        [EmailAddress]
        [Required]
        public string Email { get; set; }
        [RegularExpression("^(07)[7-9]{1}[0-9]{7}$", ErrorMessage = "Jordan PhoneNumber Please")]
        [Required]
        public string Phone { get; set; }
        [Range(18, 65)]
        [Required]
        public Nullable<int> Age { get; set; }
        [StringLength(10, ErrorMessage = "The {0} must be between {2} - {1} characters long.", MinimumLength = 1)]
        public string Job_Title { get; set; }
        [Required]
        public Nullable<bool> Gender { get; set; }
    }
}
