//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _12_2Task.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student_Customer
    {
        [Display(Name = "Student Name")]
        public int StudentId { get; set; }
        [Display(Name = "Course Name")]
        public int CourseId { get; set; }
        public string Notes { get; set; }

        public virtual Cours Cours { get; set; }
        public virtual Student Student { get; set; }
    }
}
