//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _13_2_2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Major
    {
        public int Major_Id { get; set; }
        public string Major_Name { get; set; }
        public string Major_Description { get; set; }
        public Nullable<int> Faculties_Id { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
